apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
- ../../../../components/mq/variants/cloudprovider/odf
- ../../../../components/mq/variants/nonprod
- ../../../../components/mq/variants/region/madrid
- ../../../../components/mq/variants/crr/live

resources:
- ../../../../components/mq/base

patches:
 - target:
      group: mq.ibm.com
      version: v1beta1
      kind: QueueManager
      name: qm1
   path: remote-qm1-patch.yaml
 - target:
      group: mq.ibm.com
      version: v1beta1
      kind: QueueManager
      name: qm2
   path: remote-qm2-patch.yaml
