kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: instana-agent
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  template:
    spec:
      hostAliases:
          - ip: "161.156.209.138"
            hostnames:
              - "itzvsi-t3ul3389.dte.demo.ibmcloud.com"
              - "demo-instana.itzvsi-t3ul3389.dte.demo.ibmcloud.com"
              - "agent-acceptor.itzvsi-t3ul3389.dte.demo.ibmcloud.com"
              - "otlp-http.itzvsi-t3ul3389.dte.demo.ibmcloud.com"
              - "otlp-grpc.itzvsi-t3ul3389.dte.demo.ibmcloud.com"