apiVersion: instana.io/v1
kind: InstanaAgent
metadata:
  name: instana-agent
spec:
  cluster:
    name: seb-jan-2026
  zone:
    name: madrid
  agent:
    pod:
      volumeMounts:
        - name: backend-ca
          mountPath: /opt/instana/agent/etc/backend-certs
          readOnly: true
      volumes:
        - name: backend-ca
          configMap:
            name: instana-backend-ca
    endpointHost: agent-acceptor.itzvsi-t3ul3389.dte.demo.ibmcloud.com
    endpointPort: '443'
    keysSecret: instana-agent-keys
    configuration_yaml: |

      com.instana.agent.main.sender.Backend:
        tls:
          ca-cert-path: /opt/instana/agent/etc/backend-certs/ca.crt
      
      com.instana.plugin.ibmmq:
        enabled: true
        poll_rate: 10
        support_ha: true
        queueManagers:
          SIQMSEBJAN:
            channel: 'METRICS'
          QM1:
            channel: 'METRICS'
          QM2:
            channel: 'METRICS'