apiVersion: instana.io/v1
kind: InstanaAgent
metadata:
  name: instana-agent
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  agent:
    configuration_yaml: |
      com.instana.plugin.ibmmq:
        enabled: true
        poll_rate: 10
        support_ha: true
        queueManagers:
          SIQMSEBJAN: 
            channel: 'METRICS' 
          QM1:
            channel: 'METRICS'
#          QM2:
#            channel: 'METRICS'