apiVersion: instana.io/v1
kind: InstanaAgent
metadata:
  name: instana-agent
spec:
  cluster:
    name: seb-jan-2026
  zone:
    name: madrid
  agent:
    pod:
      volumeMounts:
        - name: additional-backend-ca
          mountPath: /opt/instana/agent/etc/additional-backend-certs
          readOnly: true
      volumes:
        - name: additional-backend-ca
          configMap:
            name: instana-additional-backend-ca
    endpointHost: ingress-orange-saas.instana.io
    endpointPort: '443'
    keysSecret: instana-agent-keys
    additionalBackends:
      - endpointHost: agent-acceptor.itzvsi-t3ul3389.dte.demo.ibmcloud.com
        endpointPort: '443'
    configuration_yaml: |

      com.instana.agent.main.sender.AdditionalBackend:
        - host: agent-acceptor.itzvsi-t3ul3389.dte.demo.ibmcloud.com
          port: 443
          protocol: HTTP/2
          tls:
            ca-cert-path: /opt/instana/agent/etc/additional-backend-certs/ca.crt
      
      com.instana.plugin.ibmmq:
        enabled: true
        poll_rate: 10
        support_ha: true
        queueManagers:
          SIQMSEBJAN:
            channel: 'METRICS'
          QM1:
            channel: 'METRICS'
          QM2:
            channel: 'METRICS'