apiVersion: instana.io/v1
kind: InstanaAgent
metadata:
  name: instana-agent
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  agent:
    configuration_yaml: |
      com.instana.plugin.ibmmq:
        enabled: true
        poll_rate: 10
        support_ha: true
        queueManagers:
          SIQMSEBJAN:
            channel: 'METRICS'
          QMSI2:
            channel: 'METRICS'
          QM1:
            channel: 'METRICS'
          QM2:
            channel: 'METRICS'
          NEWQM1:
            channel: 'METRICS'
          NEWQM2:
            channel: 'METRICS'
          NEWQM3:
            channel: 'METRICS'
          NEWQM4:
            channel: 'METRICS'
          NEWQM5:
            channel: 'METRICS'
          NEWQM6:
            channel: 'METRICS'
          NEWQM7:
            channel: 'METRICS'
          NEWQM8:
            channel: 'METRICS'
          NEWQM9:
            channel: 'METRICS'
          NEWQM10:
            channel: 'METRICS'