apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mq-external-tls
spec:
  secretTemplate:
    annotations:
      cert-utils-operator.redhat-cop.io/generate-cert-info: "true"
      cert-utils-operator.redhat-cop.io/generate-java-keystores: "true"
  secretName: mq-server-certificate-secret
  duration: 2160h0m0s # 90d
  renewBefore: 360h0m0s # 15d
  subject:
    organizations:
      - mq
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - key encipherment
    - digital signature
    - server auth
    - client auth
  dnsNames:
    - 'native-ha-qm-crr-ibm-mq-qm-cp4i.apps.67ed09ced6d44283b3abd409.eu1.techzone.ibm.com'
    - 'native-ha-qm-crr-ibm-mq-qm-cp4i.apps.67ed0a2171917a5408c1aee8.ocp.techzone.ibm.com'
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
