apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: operators
spec:
  generators:
    - list:
        elements:
          - name: openshift-cert-manager
            namespace: cert-manager-operator
          - name: mq
            namespace: cp4i
          - name: cert-utils
            namespace: cert-utils-operator
          - name: openshift-telemetry
            namespace: openshift-telemetry-operator
          - name: license-service
            namespace: ibm-licensing
          - name: license-service-reporter
            namespace: ibm-ls-reporter
          #- name: openshift-cluster-observability
          #  namespace: openshift-cluster-observability-operator
  template:
    metadata:
      name: '{{name}}-operator'
      labels:
        group: applications
      annotations:
        argocd.argoproj.io/sync-wave: "100"
    spec:
      project: cp4i-operators
      source:
        path: 'components/{{name}}/operator'
      destination:
        namespace: '{{namespace}}'
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          selfHeal: true
