apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: qm1-config
    files:
      - config-routes.mqsc

generatorOptions:
  disableNameSuffixHash: true

resources: 

  - qm.yaml

  - tls/nativeha-certificate.yaml
  - tls/mq-server-certificate.yaml