apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: qm1
  annotations:
    certmanager.k8s.io/disable-auto-restart: "true"
    configmap.reloader.stakater.com/reload: "qm1-config,uniform-cluster-common-config,uniform-cluster-ini"
    secret.reloader.stakater.com/reload: "qm1-nativeha-internal-tls-secret,qm1-external-tls-secret,letsencrypt-chain"
spec:
  telemetry:
    tracing:
      # Instana library used in MQ pod to export OpenTelemetry data,
      # no Instana installs used.
      # instana:
      #   enabled: true
  license:
    accept: true
    license: PATCHED_BY_KUSTOMIZE
    metric: VirtualProcessorCore
    use: PATCHED_BY_KUSTOMIZE
  securityContext:
    supplementalGroups: [99]
  template:
    pod:
      containers:
        - env:
            - name: MQSNOAUT
              value: "yes"
            # For instana tracing,
            #- name: IBMMQ_RFH2_HEADERS_TO_EXPOSE
            #  value: 'usr.<custome element1>, usr.<custom element 2>'
            # For otel tracing
            - name: LOG_LEVEL
              value: debug
            - name: MONITOR_LEVEL
              value: debug
            - name: SPAN_FORMAT
              value: otel
            - name: OTLP_EXPORTER_GRPC_ENDPOINT
              value: 'tempo-tempostack-distributor.openshift-tempo-operator.svc.cluster.local:4317'
          name: qmgr
  queueManager:
    metrics:
      enabled: true
      tls:
        provider: openshift
    route:
      enabled: true
    name: QM1
    availability:
      type: NativeHA
      tls:
        secretName: qm1-nativeha-internal-tls-secret
    storage:
      queueManager:
        size: 10Gi
        class: PATCHED_BY_KUSTOMIZE
        deleteClaim: true
      persistedData:
        size: 10Gi
        enabled: false
        class: PATCHED_BY_KUSTOMIZE
        deleteClaim: true
      recoveryLogs:
        size: 10Gi
        enabled: false
        class: PATCHED_BY_KUSTOMIZE
        deleteClaim: true
    resources:
      limits:
        memory: 2Gi
        cpu: 2
      requests:
        cpu: 300m
        memory: 200Mi
    mqsc:
      - configMap:
          name: uniform-cluster-common-config
          items:
            - config.mqsc
      - configMap:
          name: qm1-config
          items:
            - qm1.mqsc
    ini:
      - configMap:
          name: uniform-cluster-ini
          items:
            - qm.ini
  version: 9.4.4.1-r1
  pki:
    keys:
      - name: default
        secret:
          secretName: qm1-external-tls-secret
          items:
            - tls.key
            - tls.crt
    trust:
      - name: trust
        secret:
          secretName: letsencrypt-chain
          items:
            - x1-root.crt
            - r10.crt
            - r11.crt
  web:
    enabled: true
    manualConfig:
      secret:
        name: mqwebuser-secret 
