apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: native-ha-qm
spec:
  queueManager:
    availability:
      nativeHAGroups:
        local:
          name: madrid
          tls:
            key:
              secretName: default-cert-copy
              items:
                - tls.key
                - tls.crt
        remotes: 
          - addresses:
            - native-ha-qm-crr-ibm-mq-nhacrr-cp4i.apps.67ed09ced6d44283b3abd409.eu1.techzone.ibm.com:443  
            name: frankfurt
            trust: 
              - secret:
                  secretName: default-cert-copy  
                  items:
                  - ca.crt
                  - tls.crt    
                
