apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Generate these config maps from mqsc files to support
# syntax hignlighting in tooling.
configMapGenerator:
  - name: uniform-cluster-common-config
    files:
      - config.mqsc
  - name: uniform-cluster-ini
    files:
      - qm.ini=uniform-cluster-routes.ini

generatorOptions:
  disableNameSuffixHash: true