apiVersion: operator.ibm.com/v1alpha1
kind: IBMLicensing
metadata:
  name: instance
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  datasource: datacollector
  httpsEnable: true
  version: 4.2.15
  license:
    accept: true