apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
- ../../../../components/mq/variants/cloudprovider/odf
- ../../../../components/mq/variants/nonprod
- ../../../../components/mq/variants/region/frankfurt
- ../../../../components/mq/variants/crr/recovery

resources:
- ../../../../components/mq/base

patches:
 - target:
      group: mq.ibm.com
      version: v1beta1
      kind: QueueManager
      name: native-ha-qm-crr
   path: remote-native-ha-qm-crr-patch.yaml
