apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
- ../../../../components/mq/variants/cloudprovider/odf
- ../../../../components/mq/variants/nonprod
- ../../../../components/mq/variants/region/frankfurt
- ../../../../components/mq/variants/crr/live

resources:
- ../../../../components/mq/base

patches:
 - target:
      group: mq.ibm.com
      version: v1beta1
      kind: QueueManager
      name: qm1
   path: remote-qm1-patch.yaml
 - target:
      group: mq.ibm.com
      version: v1beta1
      kind: QueueManager
      name: qm2
   path: remote-qm2-patch.yaml
 - target:
      group: cert-manager.io
      version: v1
      kind: Certificate
      name: qm1-external-tls
   path: external-tls-qm1-patch.yaml
 - target:
      group: cert-manager.io
      version: v1
      kind: Certificate
      name: qm2-external-tls
   path: external-tls-qm2-patch.yaml