apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
- ../../../../components/mq/variants/cloudprovider/odf
- ../../../../components/mq/variants/nonprod
- ../../../../components/mq/variants/region/frankfurt
- ../../../../components/mq/variants/crr/live

resources:
- ../../../../components/mq/base
