apiVersion: console.openshift.io/v1
kind: ConsoleNotification
metadata:
  name: us-east
spec:
  text: This is the cluster in Frankfurt.
  location: BannerTop 
  color: '#fff'
  backgroundColor: '#0088ce'
