apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: native-ha-qm
spec:
  queueManager:
    availability:
      nativeHAGroups:
        local:
          name: frankfurt
          tls:
            key:
              secretName: default-cert-copy
              #items:
              #  - tls.key
              #  - tls.crt
        remotes: 
          - addresses:  
            - PATCHED_BY_KUSTOMIZE
            name: madrid
            trust: 
              - secret:
                  secretName: letsencrypt-chain   
                  items:
                    - x1-root.crt
                    - r10.crt