apiVersion: tempo.grafana.com/v1alpha1
kind: TempoStack
metadata:
  name: tempostack
  namespace: openshift-tempo-operator
spec:
  #tenants:
  #  mode: openshift
  #  authentication:
  #    - tenantName: frankfurt
  #      tenantId: "a8e6a61a-abba-47e7-89a8-49b8308e6db7"
  storageSize: 20Gi 
  storage:
    secret: 
      name: tempostack-s3
      type: s3 
    tls: 
      enabled: true
      caName: s3-ca
  observability:
    tracing: {}
  template:
    gateway:
      enabled: true
    queryFrontend:
      jaegerQuery:
        enabled: true
        ingress:
          route:
            termination: edge
          type: route
