apiVersion: tempo.grafana.com/v1alpha1
kind: TempoStack
metadata:
  name: tempostack
  namespace: openshift-tempo-operator
spec:
  tenants: {}
  storageSize: 20Gi 
  storage:
    secret: 
      name: tempostack-s3
      type: s3 
    tls: 
      enabled: true
      caName: s3-ca
  observability:
    tracing: {}
  #template:
  #  queryFrontend:
  #    jaegerQuery:
  #      enabled: true
  #      ingress:
  #        route:
  #          termination: edge
  #        type: route
