apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


# See: https://letsencrypt.org/certificates/

secretGenerator:
- name: letsencrypt-chain
  files:
  - x1-root.crt=x1-root.pem
  - r10.crt=r10.pem
  type: "Opaque"

generatorOptions:
  disableNameSuffixHash: true