kind: Deployment
apiVersion: apps/v1
metadata:
  name: qm1-mq-metrics
  namespace: cp4i
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qm1-mq-metric-exporter
  template:
    metadata:
      labels:
        app: qm1-mq-metric-exporter
    spec:
      containers:
        - name: qm1-mq-metric-exporter
          image: 'image-registry.openshift-image-registry.svc:5000/cp4i/mq-metrics:latest'
          envFrom:
          - configMapRef:
              name: qm1-metrics-configuration
          - secretRef:
              name: empty-metrics-credentials
          ports:
            - containerPort: 9157
              name: web
--- 
kind: Deployment
apiVersion: apps/v1
metadata:
  name: qm2-mq-metrics
  namespace: cp4i
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qm2-mq-metric-exporter
  template:
    metadata:
      labels:
        app: qm2-mq-metric-exporter
    spec:
      containers:
        - name: qm2-mq-metric-exporter
          image: 'image-registry.openshift-image-registry.svc:5000/cp4i/mq-metrics:latest'
          envFrom:
          - configMapRef:
              name: qm2-metrics-configuration
          - secretRef:
              name: empty-metrics-credentials
          ports:
            - containerPort: 9157
              name: web