apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: qm1-metrics-podmonitor
  namespace: cp4i
spec:
  podMetricsEndpoints:
    - interval: 10s
      scheme: http
      port: web
  selector:
    matchLabels:
      app: qm1-mq-metric-exporter
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: qm2-metrics-podmonitor
  namespace: cp4i
spec:
  podMetricsEndpoints:
    - interval: 10s
      scheme: http
      port: web
  selector:
    matchLabels:
      app: qm2-mq-metric-exporter
