apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: operands
spec:
  generators:
    - list:
        elements:
          - name: mq
            namespace: cp4i
            sync-wave: "300"
          - name: reloader
            namespace: cp4i
            sync-wave: "200"
          - name: openshift-monitoring
            namespace: openshift-monitoring
            sync-wave: "300"
          - name: openshift-telemetry
            namespace: openshift-opentelemetry-operator
            sync-wave: "300"
          - name: openshift-cluster-observability
            namespace: openshift-cluster-observability-operator
            sync-wave: "300"
  template:
    metadata:
      name: '{{name}}'
      labels:
        group: applications
      annotations:
        argocd.argoproj.io/sync-wave: '{{sync-wave}}'
    spec:
      project: cp4i-operands
      source:
        path: 'envs/odf/madrid/{{name}}/'
      destination:
        namespace: '{{namespace}}'
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          selfHeal: true
