apiVersion: batch/v1 
kind: Job
metadata:
  labels:
    run: cphtestp
  name: cphtestp
spec:
  template:
    metadata:
      labels:
        run: cphtestp
    spec:
      containers:
      - env:
        - name: LICENSE
          value: accept
        - name: MQ_QMGR_HOSTNAME
          value: native-ha-qm-crr-ibm-mq.cp4i.svc.cluster.local
        - name: MQ_QMGR_PORT
          value: "1414"
        - name: MQ_QMGR_CHANNEL
          value: KAFKA
        - name: MQ_USERID
          value: 
        - name: MQ_PASSWORD
          value: 
        - name: MQ_RESPONDER_THREADS
          value: "400"
        - name: MQ_NON_PERSISTENT
          value: "0"
        #- name: MQ_MSGSIZE
        #  value: "2048"
        - name: MQ_QMGR_NAME
          value: NATIVEHAQM
        - name: MQ_DATA
          value: 
        - name: MQ_RESULTS_CSV
          value: "true"
        - name: MQ_RESULTS
          value: "false"
        image: image-registry.openshift-image-registry.svc:5000/cp4i/cphtestp
#        imagePullPolicy: IfNotPresent
        imagePullPolicy: Always
        name: cphtestp
        resources: 
          requests:
            memory: "12Gi"
            cpu: "8"
          limits:
            memory: "16Gi"
            cpu: "32"
        terminationMessagePath: /dev/termination-log
        volumeMounts:
          - name: cphdata
            mountPath: /var/cph
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: cphdata
        emptyDir: {}
      #nodeSelector: 
      # kubernetes.io/hostname : worker5.<hostname>
        