apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: new-qm-1
  annotations:
    certmanager.k8s.io/disable-auto-restart: "true"
    configmap.reloader.stakater.com/reload: "new-qm-1-configmap"
    secret.reloader.stakater.com/reload: "new-qm-1-external-tls-secret"
spec:
  license:
    accept: true
    use: NonProduction
    license: L-QWBN-T3PKLE
  template:
    pod:
      containers:
        - env:
            - name: MQSNOAUT
              value: "yes"
          name: qmgr
  queueManager:
    mqsc:
      - configMap:
          name: new-qm-1-configmap
          items:
            - tls.mqsc
    ini: 
      - configMap:    
          name: new-qm-1-configmap
          items:
            - mq.ini
    availability:
      type: SingleInstance
    name: NEWQM1
    resources:
      limits:
        cpu: 500m
      requests:
        cpu: 500m
    storage:
      defaultClass: ocs-external-storagecluster-ceph-rbd
      queueManager:
        type: persistent-claim
  version: 9.4.4.1-r1
  pki:
    keys:
      - name: default
        secret:
          secretName: new-qm-1-external-tls-secret
          items:
            - tls.key
            - tls.crt
    trust:
      - name: trust
        secret:
          secretName: new-qm-1-external-tls-secret
          items:
            - tls.crt
  web:
    enabled: true
    console:
      authentication:
        provider: manual
      authorization:
        provider: manual
    manualConfig:
      secret:
        name: mqwebuser-secret

# Made with Bob
